---

plugins:
  - react
  - 'jsx-a11y'

env:
  node: true
  browser: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb

rules:
  no-console: 0
  react/jsx-uses-vars: 1

