---

plugins:
  - react
  - import
  - 'jsx-a11y'

env:
  node: true
  browser: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

parser: babel-eslint

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:jest/recommended
  - "plugin:react-hooks/recommended"
  

rules:
  no-console: 0
  react/jsx-uses-vars: 1
  react/prop-types: 0
  import/no-unresolved: 0
